### ISSUE TITLE
 InvokeAgent operation

### ISSUE THREAD

**Issue by architect-ss** [acwwat/amazon-bedrock-agent-test-ui#1]
InvokeAgent operation: Failed to retrieve resource because it doesn't exist. Retry the request with a different resource identifier

**Comment by acwwat** [comment]
@architect-ss This error generally occurs when the `BEDROCK_AGENT_ID` environment variable is not set properly. Please ensure that you set it to the agent ID (not the name) and that you are referring to the region in which the agent exists. If needed, you can use the `AWS_DEFAULT_REGION` environment variable to set the region.
